language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - hhvm

matrix:
  allow_failures:
    - php: 7.2
    - php: 7.3
    - php: 7.4

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-stable --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
